### ISSUE TITLE
Date Picker

### ISSUE THREAD

**Issue by sandra-dudley** [sandra-dudley/baseball-app#3]
I am going to work on the date picker.

- The user needs to be able to navigate to date and back to "today" at a click of a button
- The user needs to be able to select the from and to date
- The dates prior to "today" should not be selectable
- Styling - need to make it prettier - anyone has an idea of look and feel, please let me know!

**Comment by Sandbin42** [comment]
I can (attempt to) take this on!

**Comment by sandra-dudley** [comment]
This one is all yours! Give us a shout if you need any help.

**Comment by sandra-dudley** [comment]
Thanks for sorting this out, it works great now!
